// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IBxFile: typeof import('~icons/bx/file')['default']
    VHeader: typeof import('./../components/VHeader.vue')['default']
    VMain: typeof import('./../components/VMain.vue')['default']
  }
}

export { }
